#ifndef GENERATED_ASN1SCC_HorusBinaryV3_H
#define GENERATED_ASN1SCC_HorusBinaryV3_H
/*
Code automatically generated by asn1scc tool
*/
#include "assert_override.h"
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- horusBitFlags --------------------------------------------*/
typedef struct {
    flag b0;
    flag b1;
    flag b2;
    flag b3;
    flag b4;
    flag b5;
    flag b6;
    flag b7;

} horusBitFlags;

#define ERR_BITFLAGS		41  /**/
#define ERR_BITFLAGS_B0		1  /**/
#define ERR_BITFLAGS_B1		6  /**/
#define ERR_BITFLAGS_B2		11  /**/
#define ERR_BITFLAGS_B3		16  /**/
#define ERR_BITFLAGS_B4		21  /**/
#define ERR_BITFLAGS_B5		26  /**/
#define ERR_BITFLAGS_B6		31  /**/
#define ERR_BITFLAGS_B7		36  /**/
flag horusBitFlags_IsConstraintValid(const horusBitFlags* pVal, int* pErrCode);

void horusBitFlags_Initialize(horusBitFlags* pVal);

#define ERR_UPER_ENCODE_BITFLAGS		42  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B0		2  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B1		7  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B2		12  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B3		17  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B4		22  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B5		27  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B6		32  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B7		37  /**/
#define horusBitFlags_REQUIRED_BYTES_FOR_ENCODING       1
#define horusBitFlags_REQUIRED_BITS_FOR_ENCODING        8

flag horusBitFlags_Encode(const horusBitFlags* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BITFLAGS		43  /**/
#define ERR_UPER_DECODE_BITFLAGS_B0		3  /**/
#define ERR_UPER_DECODE_BITFLAGS_B1		8  /**/
#define ERR_UPER_DECODE_BITFLAGS_B2		13  /**/
#define ERR_UPER_DECODE_BITFLAGS_B3		18  /**/
#define ERR_UPER_DECODE_BITFLAGS_B4		23  /**/
#define ERR_UPER_DECODE_BITFLAGS_B5		28  /**/
#define ERR_UPER_DECODE_BITFLAGS_B6		33  /**/
#define ERR_UPER_DECODE_BITFLAGS_B7		38  /**/
flag horusBitFlags_Decode(horusBitFlags* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- horusCustomFieldValues --------------------------------------------*/
typedef char horusCustomFieldValues_horusStr[256];


typedef struct {
    int nCount;
    asn1SccSint arr[4];
} horusCustomFieldValues_horusInt;


typedef struct {
    int nCount;
    asn1Real arr[4];
} horusCustomFieldValues_horusReal;

typedef enum {
    CustomFieldValues_NONE,
    horusStr_PRESENT,
    horusInt_PRESENT,
    horusReal_PRESENT,
    horusBool_PRESENT
} horusCustomFieldValues_selection;

typedef union {
    horusCustomFieldValues_horusStr horusStr;
    horusCustomFieldValues_horusInt horusInt;
    horusCustomFieldValues_horusReal horusReal;
    horusBitFlags horusBool;
} horusCustomFieldValues_unchecked_union;

typedef struct {
    horusCustomFieldValues_selection kind;

    horusCustomFieldValues_unchecked_union u;
} horusCustomFieldValues;

#define ERR_CUSTOMFIELDVALUES_HORUSSTR		46  /*(FROM("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_ +/=-.")^SIZE (0..255))*/
flag horusCustomFieldValues_horusStr_IsConstraintValid(const horusCustomFieldValues_horusStr pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES_HORUSINT		56  /*(SIZE(1..4))*/
#define ERR_CUSTOMFIELDVALUES_HORUSINT_ELM		51  /**/
flag horusCustomFieldValues_horusInt_IsConstraintValid(const horusCustomFieldValues_horusInt* pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES_HORUSREAL		66  /*(SIZE(1..4))*/
#define ERR_CUSTOMFIELDVALUES_HORUSREAL_ELM		61  /**/
flag horusCustomFieldValues_horusReal_IsConstraintValid(const horusCustomFieldValues_horusReal* pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES		76  /**/
#define ERR_CUSTOMFIELDVALUES_HORUSBOOL		71  /**/
flag horusCustomFieldValues_IsConstraintValid(const horusCustomFieldValues* pVal, int* pErrCode);

void horusCustomFieldValues_horusStr_Initialize(horusCustomFieldValues_horusStr pVal);
void horusCustomFieldValues_horusInt_Initialize(horusCustomFieldValues_horusInt* pVal);
void horusCustomFieldValues_horusReal_Initialize(horusCustomFieldValues_horusReal* pVal);
void horusCustomFieldValues_Initialize(horusCustomFieldValues* pVal);

#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES		77  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSSTR		47  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSINT		57  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSINT_ELM		52  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSREAL		67  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSREAL_ELM		62  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSBOOL		72  /**/
#define horusCustomFieldValues_REQUIRED_BYTES_FOR_ENCODING       225
#define horusCustomFieldValues_REQUIRED_BITS_FOR_ENCODING        1795

flag horusCustomFieldValues_Encode(const horusCustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CUSTOMFIELDVALUES		78  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSSTR		48  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT		58  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT_ELM		53  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL		68  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL_ELM		63  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSBOOL		73  /**/
flag horusCustomFieldValues_Decode(horusCustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- horusAdditionalSensorType --------------------------------------------*/
typedef char horusAdditionalSensorType_name[21];
typedef struct {
    unsigned long name:1;
    unsigned long values:1;
} horusAdditionalSensorType_exist;
typedef struct {
    horusAdditionalSensorType_name name;
    horusCustomFieldValues values;

    horusAdditionalSensorType_exist exist;

} horusAdditionalSensorType;

#define ERR_ADDITIONALSENSORTYPE_NAME		81  /*(FROM("abcdefghijklmnopqrstuvwxyz0123456789-")^SIZE (1..20))*/
flag horusAdditionalSensorType_name_IsConstraintValid(const horusAdditionalSensorType_name pVal, int* pErrCode);

#define ERR_ADDITIONALSENSORTYPE		91  /**/
#define ERR_ADDITIONALSENSORTYPE_VALUES		86  /**/
flag horusAdditionalSensorType_IsConstraintValid(const horusAdditionalSensorType* pVal, int* pErrCode);

void horusAdditionalSensorType_name_Initialize(horusAdditionalSensorType_name pVal);
void horusAdditionalSensorType_Initialize(horusAdditionalSensorType* pVal);

#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE		92  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE_NAME		82  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE_VALUES		87  /**/
#define horusAdditionalSensorType_REQUIRED_BYTES_FOR_ENCODING       241
#define horusAdditionalSensorType_REQUIRED_BITS_FOR_ENCODING        1922

flag horusAdditionalSensorType_Encode(const horusAdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE		93  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE_NAME		83  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE_VALUES		88  /**/
flag horusAdditionalSensorType_Decode(horusAdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    horusAdditionalSensorType arr[4];
} horusAdditionalSensors;

#define ERR_ADDITIONALSENSORS		101  /*(SIZE(1..4))*/
#define ERR_ADDITIONALSENSORS_ELM		96  /**/
flag horusAdditionalSensors_IsConstraintValid(const horusAdditionalSensors* pVal, int* pErrCode);

void horusAdditionalSensors_Initialize(horusAdditionalSensors* pVal);

#define ERR_UPER_ENCODE_ADDITIONALSENSORS		102  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORS_ELM		97  /**/
#define horusAdditionalSensors_REQUIRED_BYTES_FOR_ENCODING       962
#define horusAdditionalSensors_REQUIRED_BITS_FOR_ENCODING        7690

flag horusAdditionalSensors_Encode(const horusAdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ADDITIONALSENSORS		103  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORS_ELM		98  /**/
flag horusAdditionalSensors_Decode(horusAdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- horusTemperatureSensors --------------------------------------------*/
typedef int16_t horusTemperatureSensors_internal;

typedef int16_t horusTemperatureSensors_external;

typedef int16_t horusTemperatureSensors_custom1;

typedef int16_t horusTemperatureSensors_custom2;

typedef struct {
    unsigned long internal:1;
    unsigned long external:1;
    unsigned long custom1:1;
    unsigned long custom2:1;
} horusTemperatureSensors_exist;
typedef struct {
    horusTemperatureSensors_internal internal;
    horusTemperatureSensors_external external;
    horusTemperatureSensors_custom1 custom1;
    horusTemperatureSensors_custom2 custom2;

    horusTemperatureSensors_exist exist;

} horusTemperatureSensors;

#define ERR_TEMPERATURESENSORS_INTERNAL		106  /*(-1023..1023)*/
flag horusTemperatureSensors_internal_IsConstraintValid(const horusTemperatureSensors_internal* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_EXTERNAL		111  /*(-1023..1023)*/
flag horusTemperatureSensors_external_IsConstraintValid(const horusTemperatureSensors_external* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_CUSTOM1		116  /*(-1023..1023)*/
flag horusTemperatureSensors_custom1_IsConstraintValid(const horusTemperatureSensors_custom1* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_CUSTOM2		121  /*(-1023..1023)*/
flag horusTemperatureSensors_custom2_IsConstraintValid(const horusTemperatureSensors_custom2* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS		126  /**/
flag horusTemperatureSensors_IsConstraintValid(const horusTemperatureSensors* pVal, int* pErrCode);

void horusTemperatureSensors_internal_Initialize(horusTemperatureSensors_internal* pVal);
void horusTemperatureSensors_external_Initialize(horusTemperatureSensors_external* pVal);
void horusTemperatureSensors_custom1_Initialize(horusTemperatureSensors_custom1* pVal);
void horusTemperatureSensors_custom2_Initialize(horusTemperatureSensors_custom2* pVal);
void horusTemperatureSensors_Initialize(horusTemperatureSensors* pVal);

#define ERR_UPER_ENCODE_TEMPERATURESENSORS		127  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_INTERNAL		107  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_EXTERNAL		112  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_CUSTOM1		117  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_CUSTOM2		122  /**/
#define horusTemperatureSensors_REQUIRED_BYTES_FOR_ENCODING       6
#define horusTemperatureSensors_REQUIRED_BITS_FOR_ENCODING        48

flag horusTemperatureSensors_Encode(const horusTemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TEMPERATURESENSORS		128  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_INTERNAL		108  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_EXTERNAL		113  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM1		118  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM2		123  /**/
flag horusTemperatureSensors_Decode(horusTemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- horusMilliVoltSensors --------------------------------------------*/
typedef uint16_t horusMilliVoltSensors_battery;

typedef uint16_t horusMilliVoltSensors_solar;

typedef uint16_t horusMilliVoltSensors_custom1;

typedef uint16_t horusMilliVoltSensors_custom2;

typedef struct {
    unsigned long battery:1;
    unsigned long solar:1;
    unsigned long custom1:1;
    unsigned long custom2:1;
} horusMilliVoltSensors_exist;
typedef struct {
    horusMilliVoltSensors_battery battery;
    horusMilliVoltSensors_solar solar;
    horusMilliVoltSensors_custom1 custom1;
    horusMilliVoltSensors_custom2 custom2;

    horusMilliVoltSensors_exist exist;

} horusMilliVoltSensors;

#define ERR_MILLIVOLTSENSORS_BATTERY		131  /*(0..16383)*/
flag horusMilliVoltSensors_battery_IsConstraintValid(const horusMilliVoltSensors_battery* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_SOLAR		136  /*(0..16383)*/
flag horusMilliVoltSensors_solar_IsConstraintValid(const horusMilliVoltSensors_solar* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_CUSTOM1		141  /*(0..16383)*/
flag horusMilliVoltSensors_custom1_IsConstraintValid(const horusMilliVoltSensors_custom1* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_CUSTOM2		146  /*(0..16383)*/
flag horusMilliVoltSensors_custom2_IsConstraintValid(const horusMilliVoltSensors_custom2* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS		151  /**/
flag horusMilliVoltSensors_IsConstraintValid(const horusMilliVoltSensors* pVal, int* pErrCode);

void horusMilliVoltSensors_battery_Initialize(horusMilliVoltSensors_battery* pVal);
void horusMilliVoltSensors_solar_Initialize(horusMilliVoltSensors_solar* pVal);
void horusMilliVoltSensors_custom1_Initialize(horusMilliVoltSensors_custom1* pVal);
void horusMilliVoltSensors_custom2_Initialize(horusMilliVoltSensors_custom2* pVal);
void horusMilliVoltSensors_Initialize(horusMilliVoltSensors* pVal);

#define ERR_UPER_ENCODE_MILLIVOLTSENSORS		152  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_BATTERY		132  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_SOLAR		137  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_CUSTOM1		142  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_CUSTOM2		147  /**/
#define horusMilliVoltSensors_REQUIRED_BYTES_FOR_ENCODING       8
#define horusMilliVoltSensors_REQUIRED_BITS_FOR_ENCODING        60

flag horusMilliVoltSensors_Encode(const horusMilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MILLIVOLTSENSORS		153  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_BATTERY		133  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_SOLAR		138  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM1		143  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM2		148  /**/
flag horusMilliVoltSensors_Decode(horusMilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    horuspsmNotActive = 0,
    horusenabled = 1,
    horusacquisition = 2,
    horustracking = 3,
    horusoptimised = 4,
    horusinactive = 5
} horusGnssPowerSaveState;

// please use the following macros to avoid breaking code.
#define horusGnssPowerSaveState_psmNotActive horuspsmNotActive
#define horusGnssPowerSaveState_enabled horusenabled
#define horusGnssPowerSaveState_acquisition horusacquisition
#define horusGnssPowerSaveState_tracking horustracking
#define horusGnssPowerSaveState_optimised horusoptimised
#define horusGnssPowerSaveState_inactive horusinactive

#define ERR_GNSSPOWERSAVESTATE		156  /*psmNotActive | enabled | acquisition | tracking | optimised | inactive*/
flag horusGnssPowerSaveState_IsConstraintValid(const horusGnssPowerSaveState* pVal, int* pErrCode);

void horusGnssPowerSaveState_Initialize(horusGnssPowerSaveState* pVal);

#define ERR_UPER_ENCODE_GNSSPOWERSAVESTATE		157  /**/
#define horusGnssPowerSaveState_REQUIRED_BYTES_FOR_ENCODING       1
#define horusGnssPowerSaveState_REQUIRED_BITS_FOR_ENCODING        3

flag horusGnssPowerSaveState_Encode(const horusGnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GNSSPOWERSAVESTATE		158  /**/
flag horusGnssPowerSaveState_Decode(horusGnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- horusTelemetry --------------------------------------------*/
typedef char horusTelemetry_payloadCallsign[16];
typedef uint16_t horusTelemetry_sequenceNumber;

typedef int32_t horusTelemetry_timeOfDaySeconds;

typedef int32_t horusTelemetry_latitude;

typedef int32_t horusTelemetry_longitude;

typedef int32_t horusTelemetry_altitudeMeters;

typedef uint16_t horusTelemetry_velocityHorizontalKilometersPerHour;

typedef uint8_t horusTelemetry_gnssSatellitesVisible;

typedef int16_t horusTelemetry_ascentRateCentimetersPerSecond;

typedef uint16_t horusTelemetry_pressurehPa_x10;

typedef uint8_t horusTelemetry_humidityPercentage;



typedef struct {
    int nCount;
    asn1SccSint arr[8];
} horusTelemetry_counts;
typedef struct {
    int nCount;
    byte arr[255];
} horusTelemetry_customData;

typedef struct {
    unsigned long extensionMarkerForASN1CC:1;
    unsigned long extraSensors:1;
    unsigned long velocityHorizontalKilometersPerHour:1;
    unsigned long gnssSatellitesVisible:1;
    unsigned long ascentRateCentimetersPerSecond:1;
    unsigned long pressurehPa_x10:1;
    unsigned long temperatureCelsius_x10:1;
    unsigned long humidityPercentage:1;
    unsigned long milliVolts:1;
    unsigned long counts:1;
    unsigned long gnssPowerSaveState:1;
    unsigned long customData:1;
} horusTelemetry_exist;
typedef struct {
    flag extensionMarkerForASN1CC;
    horusTelemetry_payloadCallsign payloadCallsign;
    horusTelemetry_sequenceNumber sequenceNumber;
    horusTelemetry_timeOfDaySeconds timeOfDaySeconds;
    horusTelemetry_latitude latitude;
    horusTelemetry_longitude longitude;
    horusTelemetry_altitudeMeters altitudeMeters;
    horusAdditionalSensors extraSensors;
    horusTelemetry_velocityHorizontalKilometersPerHour velocityHorizontalKilometersPerHour;
    horusTelemetry_gnssSatellitesVisible gnssSatellitesVisible;
    horusTelemetry_ascentRateCentimetersPerSecond ascentRateCentimetersPerSecond;
    horusTelemetry_pressurehPa_x10 pressurehPa_x10;
    horusTemperatureSensors temperatureCelsius_x10;
    horusTelemetry_humidityPercentage humidityPercentage;
    horusMilliVoltSensors milliVolts;
    horusTelemetry_counts counts;
    horusGnssPowerSaveState gnssPowerSaveState;
    horusTelemetry_customData customData;

    horusTelemetry_exist exist;

} horusTelemetry;

#define ERR_TELEMETRY_PAYLOADCALLSIGN		166  /*(FROM("-/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")^SIZE (1..15))*/
flag horusTelemetry_payloadCallsign_IsConstraintValid(const horusTelemetry_payloadCallsign pVal, int* pErrCode);

#define ERR_TELEMETRY_SEQUENCENUMBER		171  /*(0..65535)*/
flag horusTelemetry_sequenceNumber_IsConstraintValid(const horusTelemetry_sequenceNumber* pVal, int* pErrCode);

#define ERR_TELEMETRY_TIMEOFDAYSECONDS		176  /*(-1..86400)*/
flag horusTelemetry_timeOfDaySeconds_IsConstraintValid(const horusTelemetry_timeOfDaySeconds* pVal, int* pErrCode);

#define ERR_TELEMETRY_LATITUDE		181  /*(-9000000..9000000)*/
flag horusTelemetry_latitude_IsConstraintValid(const horusTelemetry_latitude* pVal, int* pErrCode);

#define ERR_TELEMETRY_LONGITUDE		186  /*(-18000000..18000000)*/
flag horusTelemetry_longitude_IsConstraintValid(const horusTelemetry_longitude* pVal, int* pErrCode);

#define ERR_TELEMETRY_ALTITUDEMETERS		191  /*(-1000..50000)*/
flag horusTelemetry_altitudeMeters_IsConstraintValid(const horusTelemetry_altitudeMeters* pVal, int* pErrCode);

#define ERR_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		201  /*(0..512)*/
flag horusTelemetry_velocityHorizontalKilometersPerHour_IsConstraintValid(const horusTelemetry_velocityHorizontalKilometersPerHour* pVal, int* pErrCode);

#define ERR_TELEMETRY_GNSSSATELLITESVISIBLE		206  /*(0..31)*/
flag horusTelemetry_gnssSatellitesVisible_IsConstraintValid(const horusTelemetry_gnssSatellitesVisible* pVal, int* pErrCode);

#define ERR_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		211  /*(-32767..32767)*/
flag horusTelemetry_ascentRateCentimetersPerSecond_IsConstraintValid(const horusTelemetry_ascentRateCentimetersPerSecond* pVal, int* pErrCode);

#define ERR_TELEMETRY_PRESSUREHPA_X10		216  /*(0..12000)*/
flag horusTelemetry_pressurehPa_x10_IsConstraintValid(const horusTelemetry_pressurehPa_x10* pVal, int* pErrCode);

#define ERR_TELEMETRY_HUMIDITYPERCENTAGE		226  /*(0..100)*/
flag horusTelemetry_humidityPercentage_IsConstraintValid(const horusTelemetry_humidityPercentage* pVal, int* pErrCode);

#define ERR_TELEMETRY_COUNTS		241  /*(SIZE(1..8))*/
#define ERR_TELEMETRY_COUNTS_ELM		236  /**/
flag horusTelemetry_counts_IsConstraintValid(const horusTelemetry_counts* pVal, int* pErrCode);

#define ERR_TELEMETRY_CUSTOMDATA		256  /*(SIZE (0..255))*/
flag horusTelemetry_customData_IsConstraintValid(const horusTelemetry_customData* pVal, int* pErrCode);

#define ERR_TELEMETRY		261  /**/
#define ERR_TELEMETRY_EXTENSIONMARKERFORASN1CC		161  /**/
#define ERR_TELEMETRY_EXTRASENSORS		196  /**/
#define ERR_TELEMETRY_TEMPERATURECELSIUS_X10		221  /**/
#define ERR_TELEMETRY_MILLIVOLTS		231  /**/
#define ERR_TELEMETRY_GNSSPOWERSAVESTATE_2		251  /**/
flag horusTelemetry_IsConstraintValid(const horusTelemetry* pVal, int* pErrCode);

void horusTelemetry_payloadCallsign_Initialize(horusTelemetry_payloadCallsign pVal);
void horusTelemetry_sequenceNumber_Initialize(horusTelemetry_sequenceNumber* pVal);
void horusTelemetry_timeOfDaySeconds_Initialize(horusTelemetry_timeOfDaySeconds* pVal);
void horusTelemetry_latitude_Initialize(horusTelemetry_latitude* pVal);
void horusTelemetry_longitude_Initialize(horusTelemetry_longitude* pVal);
void horusTelemetry_altitudeMeters_Initialize(horusTelemetry_altitudeMeters* pVal);
void horusTelemetry_velocityHorizontalKilometersPerHour_Initialize(horusTelemetry_velocityHorizontalKilometersPerHour* pVal);
void horusTelemetry_gnssSatellitesVisible_Initialize(horusTelemetry_gnssSatellitesVisible* pVal);
void horusTelemetry_ascentRateCentimetersPerSecond_Initialize(horusTelemetry_ascentRateCentimetersPerSecond* pVal);
void horusTelemetry_pressurehPa_x10_Initialize(horusTelemetry_pressurehPa_x10* pVal);
void horusTelemetry_humidityPercentage_Initialize(horusTelemetry_humidityPercentage* pVal);
void horusTelemetry_counts_Initialize(horusTelemetry_counts* pVal);
void horusTelemetry_customData_Initialize(horusTelemetry_customData* pVal);
void horusTelemetry_Initialize(horusTelemetry* pVal);

#define ERR_UPER_ENCODE_TELEMETRY		262  /**/
#define ERR_UPER_ENCODE_TELEMETRY_EXTENSIONMARKERFORASN1CC		162  /**/
#define ERR_UPER_ENCODE_TELEMETRY_PAYLOADCALLSIGN		167  /**/
#define ERR_UPER_ENCODE_TELEMETRY_SEQUENCENUMBER		172  /**/
#define ERR_UPER_ENCODE_TELEMETRY_TIMEOFDAYSECONDS		177  /**/
#define ERR_UPER_ENCODE_TELEMETRY_LATITUDE		182  /**/
#define ERR_UPER_ENCODE_TELEMETRY_LONGITUDE		187  /**/
#define ERR_UPER_ENCODE_TELEMETRY_ALTITUDEMETERS		192  /**/
#define ERR_UPER_ENCODE_TELEMETRY_EXTRASENSORS		197  /**/
#define ERR_UPER_ENCODE_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		202  /**/
#define ERR_UPER_ENCODE_TELEMETRY_GNSSSATELLITESVISIBLE		207  /**/
#define ERR_UPER_ENCODE_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		212  /**/
#define ERR_UPER_ENCODE_TELEMETRY_PRESSUREHPA_X10		217  /**/
#define ERR_UPER_ENCODE_TELEMETRY_TEMPERATURECELSIUS_X10		222  /**/
#define ERR_UPER_ENCODE_TELEMETRY_HUMIDITYPERCENTAGE		227  /**/
#define ERR_UPER_ENCODE_TELEMETRY_MILLIVOLTS		232  /**/
#define ERR_UPER_ENCODE_TELEMETRY_COUNTS		242  /**/
#define ERR_UPER_ENCODE_TELEMETRY_COUNTS_ELM		237  /**/
#define ERR_UPER_ENCODE_TELEMETRY_GNSSPOWERSAVESTATE_2		252  /**/
#define ERR_UPER_ENCODE_TELEMETRY_CUSTOMDATA		257  /**/
#define horusTelemetry_REQUIRED_BYTES_FOR_ENCODING       1336
#define horusTelemetry_REQUIRED_BITS_FOR_ENCODING        10687

flag horusTelemetry_Encode(const horusTelemetry* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TELEMETRY		263  /**/
#define ERR_UPER_DECODE_TELEMETRY_EXTENSIONMARKERFORASN1CC		163  /**/
#define ERR_UPER_DECODE_TELEMETRY_PAYLOADCALLSIGN		168  /**/
#define ERR_UPER_DECODE_TELEMETRY_SEQUENCENUMBER		173  /**/
#define ERR_UPER_DECODE_TELEMETRY_TIMEOFDAYSECONDS		178  /**/
#define ERR_UPER_DECODE_TELEMETRY_LATITUDE		183  /**/
#define ERR_UPER_DECODE_TELEMETRY_LONGITUDE		188  /**/
#define ERR_UPER_DECODE_TELEMETRY_ALTITUDEMETERS		193  /**/
#define ERR_UPER_DECODE_TELEMETRY_EXTRASENSORS		198  /**/
#define ERR_UPER_DECODE_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		203  /**/
#define ERR_UPER_DECODE_TELEMETRY_GNSSSATELLITESVISIBLE		208  /**/
#define ERR_UPER_DECODE_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		213  /**/
#define ERR_UPER_DECODE_TELEMETRY_PRESSUREHPA_X10		218  /**/
#define ERR_UPER_DECODE_TELEMETRY_TEMPERATURECELSIUS_X10		223  /**/
#define ERR_UPER_DECODE_TELEMETRY_HUMIDITYPERCENTAGE		228  /**/
#define ERR_UPER_DECODE_TELEMETRY_MILLIVOLTS		233  /**/
#define ERR_UPER_DECODE_TELEMETRY_COUNTS		243  /**/
#define ERR_UPER_DECODE_TELEMETRY_COUNTS_ELM		238  /**/
#define ERR_UPER_DECODE_TELEMETRY_GNSSPOWERSAVESTATE_2		253  /**/
#define ERR_UPER_DECODE_TELEMETRY_CUSTOMDATA		258  /**/
flag horusTelemetry_Decode(horusTelemetry* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
