import type { Schema, SchemaField } from "../types/schema";
import type { ConfigState } from "../types/config";
import {
  getSortedSectionKeys,
  getSectionFieldKeys,
  getField,
  resolveAliasDefine,
} from "./schema-registry";
import { formatValue } from "./format-value";

/** Get the effective value for a field: config value if present, else schema default */
function effectiveValue(
  config: ConfigState,
  sectionKey: string,
  fieldKey: string,
  field: SchemaField
): unknown {
  const v = config[sectionKey]?.[fieldKey];
  return v !== undefined ? v : field.default;
}

/**
 * Generate the content of config_generated.h (included via config.h when RS41NG_USE_GENERATED_CONFIG).
 * Output is identical to what scripts/generate_config.ts produces for the same input.
 */
export function generateConfigH(schema: Schema, config: ConfigState): string {
  const lines: string[] = [];

  lines.push(
    "// RS41ng Firmware Configuration",
    "// Generated by RS41ng Config Generator - DO NOT EDIT MANUALLY",
    "// To modify: edit config.yaml and run the config generator",
    ""
  );

  lines.push(
    "// Experimental support for Graw DFM-17 radiosondes added! Please test and report any issues!",
    "// WARNING: Using a DFM-17 as a primary flight tracker is NOT recommended yet!",
    "// NOTE: DFM-17 radiosondes require a GPS lock (and clear visibility to the sky) to calibrate its internal oscillator.",
    "// DFM-17 transmissions, especially APRS, may not decode correctly because of incorrect timing before the internal oscillator has been calibrated.",
    ""
  );

  lines.push("#ifndef __CONFIG_GENERATED_H", "#define __CONFIG_GENERATED_H", "");

  // Hardware type is now defined via CMake compiler flags (-DRS41=1, -DRS41_RSM4X4=1, -DDFM17=1),
  // not in config.h. The build script (docker_build.sh) reads hardware.type from config.yaml
  // and passes the correct flags. We only emit a comment for reference.
  const hwTypeField = getField(schema, "hardware", "type");
  const hwValue =
    config.hardware?.type ?? hwTypeField?.default ?? "RS41";

  lines.push(
    "// Hardware type: " + hwValue,
    "// NOTE: Hardware type is defined via CMake compiler flags, not in this file.",
    "// See docker_build.sh or pass -DRS41=1 / -DRS41_RSM4X4=1 / -DDFM17=1 to cmake.",
    ""
  );

  // All non-hardware sections
  for (const sectionKey of getSortedSectionKeys(schema)) {
    if (sectionKey === "hardware") continue;

    // Collect config.h fields (exclude config.c fields and toggle-style defines)
    const configHFields: Array<[string, SchemaField]> = getSectionFieldKeys(
      schema,
      sectionKey
    )
      .map((fieldKey) => [fieldKey, getField(schema, sectionKey, fieldKey)] as const)
      .filter(
        (pair): pair is [string, SchemaField] =>
          pair[1] !== null &&
          (pair[1].file ?? "config.h") === "config.h" &&
          pair[1].define_style !== "toggle"
      );

    if (configHFields.length === 0) continue;

    const sectionMeta = schema[sectionKey] as { _section?: string };
    lines.push(`/**`, ` * ${sectionMeta._section ?? sectionKey}`, ` */`, "");

    for (const [fieldKey, field] of configHFields) {
      // Emit enum constant definitions before the field that uses them
      if (field.enum_defines && field.enum_defines.length > 0) {
        for (const ed of field.enum_defines) {
          lines.push(`#define ${ed.define} ${ed.value}`);
        }
        lines.push("");
      }

      // alias_of: emit #define X Y referencing the aliased define name
      if (field.alias_of) {
        const refDefine = resolveAliasDefine(schema, field.alias_of);
        if (refDefine) {
          lines.push(`#define ${field.define} ${refDefine}`);
        }
        continue;
      }

      const value = effectiveValue(config, sectionKey, fieldKey, field);
      if (value === undefined || value === null) continue;

      const formatted = formatValue(field, value);
      lines.push(`#define ${field.define} ${formatted}`);
    }

    lines.push("");

    // Bus mutual-exclusions span multiple sections and can't be expressed in the
    // schema's per-field model, so they are emitted as compile-time #error guards.
    if (sectionKey === "gps") {
      lines.push(
        "#if (GPS_NMEA_OUTPUT_VIA_SERIAL_PORT_ENABLE) && ((RADIO_SI5351_ENABLE) || (SENSOR_BMP280_ENABLE))",
        "#error GPS NMEA output via serial port cannot be enabled simultaneously with the I2C bus.",
        "#endif",
        ""
      );
    }

    if (sectionKey === "sensors") {
      lines.push(
        "#if (PULSE_COUNTER_ENABLE) && ((GPS_NMEA_OUTPUT_VIA_SERIAL_PORT_ENABLE) || (RADIO_SI5351_ENABLE) || (SENSOR_BMP280_ENABLE))",
        "#error Pulse counter cannot be enabled simultaneously with GPS NMEA output or I2C bus sensors.",
        "#endif",
        ""
      );
    }
  }

  lines.push('#include "config_internal.h"', "", "#endif", "");

  return lines.join("\n");
}
