import { describe, it, expect } from "vitest";
import type { Schema } from "@/types/schema";
import { generateConfigH } from "@/config/generate-header";

function makeSchema(): Schema {
  return {
    hardware: {
      _section: "Hardware",
      _tier: "simple",
      _order: 0,
      type: {
        define: "HARDWARE_TYPE",
        type: "enum",
        label: "Hardware",
        tier: "simple",
        default: "RS41",
        values: [
          { value: "RS41", label: "RS41" },
          { value: "DFM17", label: "DFM-17" },
        ],
        define_style: "toggle",
      },
    },
    global: {
      _section: "Global",
      _tier: "simple",
      _order: 1,
      callsign: {
        define: "CALLSIGN",
        type: "string",
        label: "Callsign",
        tier: "simple",
        default: "N0CALL",
        validation: { required: true, max_length: 6 },
      },
    },
    radio_si4032: {
      _section: "Radio SI4032",
      _tier: "simple",
      _order: 2,
      tx_power: {
        define: "RADIO_SI4032_TX_POWER",
        type: "integer",
        label: "TX Power",
        tier: "simple",
        default: 7,
        validation: { min: 0, max: 7 },
      },
      tx_aprs: {
        define: "RADIO_SI4032_TX_APRS",
        type: "bool",
        label: "APRS",
        tier: "simple",
        default: false,
      },
      // This field points to config.c — should NOT appear in config.h
      comment_field: {
        define: "aprs_comments",
        type: "string_array",
        label: "APRS Comments",
        tier: "intermediate",
        file: "config.c",
        default: ["test"],
      },
      // Toggle-style field — should NOT appear as a #define line
      toggle_field: {
        define: "SOME_TOGGLE",
        type: "bool",
        label: "Toggle",
        tier: "advanced",
        default: false,
        define_style: "toggle",
      },
    },
    gps: {
      _section: "GPS",
      _tier: "advanced",
      _order: 3,
      nmea_output_enable: {
        define: "GPS_NMEA_OUTPUT_VIA_SERIAL_PORT_ENABLE",
        type: "bool",
        label: "NMEA Output",
        tier: "advanced",
        default: false,
      },
    },
    sensors: {
      _section: "Sensors",
      _tier: "advanced",
      _order: 4,
      bmp280_enable: {
        define: "SENSOR_BMP280_ENABLE",
        type: "bool",
        label: "BMP280",
        tier: "advanced",
        default: false,
      },
    },
  } as unknown as Schema;
}

describe("generateConfigH — file structure", () => {
  it("starts with generated file comment", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain("// RS41ng Firmware Configuration");
    expect(out).toContain("// Generated by RS41ng Config Generator");
  });

  it("includes header guard", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain("#ifndef __CONFIG_GENERATED_H");
    expect(out).toContain("#define __CONFIG_GENERATED_H");
    expect(out).toContain("#endif");
  });

  it("includes config_internal.h at the end", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain('#include "config_internal.h"');
  });
});

describe("generateConfigH — hardware toggle", () => {
  it("emits hardware type comment for RS41 config", () => {
    const out = generateConfigH(makeSchema(), { hardware: { type: "RS41" } });
    expect(out).toContain("// Hardware type: RS41");
    expect(out).toContain("CMake compiler flags");
  });

  it("emits hardware type comment for DFM17 config", () => {
    const out = generateConfigH(makeSchema(), { hardware: { type: "DFM17" } });
    expect(out).toContain("// Hardware type: DFM17");
  });

  it("defaults to RS41 when hardware config is absent", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain("// Hardware type: RS41");
  });

  it("does not emit hardware defines (handled by CMake flags)", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).not.toMatch(/^#define RS41$/m);
    expect(out).not.toMatch(/^#define DFM17$/m);
    expect(out).not.toContain("#if !defined(RS41)");
  });
});

describe("generateConfigH — field emission", () => {
  it("emits string field as quoted #define", () => {
    const out = generateConfigH(makeSchema(), { global: { callsign: "OH2A" } });
    expect(out).toContain('#define CALLSIGN "OH2A"');
  });

  it("uses schema default when field not in config", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain('#define CALLSIGN "N0CALL"');
  });

  it("emits integer field as numeric #define", () => {
    const out = generateConfigH(makeSchema(), {
      radio_si4032: { tx_power: 5 },
    });
    expect(out).toContain("#define RADIO_SI4032_TX_POWER 5");
  });

  it("emits bool field as true/false", () => {
    const out = generateConfigH(makeSchema(), {
      radio_si4032: { tx_aprs: true },
    });
    expect(out).toContain("#define RADIO_SI4032_TX_APRS true");
  });

  it("does NOT emit config.c fields in config.h", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).not.toContain("aprs_comments");
  });

  it("does NOT emit define_style=toggle fields as #define lines", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).not.toContain("#define SOME_TOGGLE");
  });

  it("emits section comment header", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain("* Global");
    expect(out).toContain("* Radio SI4032");
  });
});

describe("generateConfigH — alias_of", () => {
  it("emits #define ALIAS_DEFINE ORIGINAL_DEFINE for alias fields", () => {
    const schema: Schema = {
      global: {
        _section: "Global",
        _tier: "simple",
        _order: 0,
        callsign: {
          define: "CALLSIGN",
          type: "string",
          label: "Callsign",
          tier: "simple",
          default: "N0CALL",
        },
      },
      radio_si4032: {
        _section: "Radio",
        _tier: "simple",
        _order: 1,
        aprs_callsign: {
          define: "APRS_CALLSIGN",
          type: "string",
          label: "APRS Callsign",
          tier: "intermediate",
          alias_of: "global.callsign",
        },
      },
      hardware: {
        _section: "Hardware",
        _tier: "simple",
        _order: 99,
        type: {
          define: "HW",
          type: "enum",
          label: "HW",
          tier: "simple",
          default: "RS41",
          define_style: "toggle",
        },
      },
    } as unknown as Schema;
    const out = generateConfigH(schema, {});
    expect(out).toContain("#define APRS_CALLSIGN CALLSIGN");
  });
});

describe("generateConfigH — enum_defines", () => {
  it("emits enum constant #defines before the field that uses them", () => {
    const schema: Schema = {
      hardware: {
        _section: "Hardware",
        _tier: "simple",
        _order: 0,
        type: {
          define: "HW",
          type: "enum",
          label: "HW",
          tier: "simple",
          default: "RS41",
          define_style: "toggle",
        },
      },
      gps: {
        _section: "GPS",
        _tier: "advanced",
        _order: 1,
        dynamic_model: {
          define: "GPS_DYNAMIC_MODEL",
          type: "enum_constant",
          label: "Dynamic Model",
          tier: "advanced",
          default: 6,
          enum_defines: [
            { define: "GPS_DYNAMIC_MODEL_AIRBORNE_1G", value: 6 },
            { define: "GPS_DYNAMIC_MODEL_PORTABLE", value: 0 },
          ],
          values: [
            { value: 0, label: "Portable" },
            { value: 6, label: "Airborne <1g" },
          ],
        },
      },
    } as unknown as Schema;

    const out = generateConfigH(schema, {});
    const posConst = out.indexOf("#define GPS_DYNAMIC_MODEL_AIRBORNE_1G");
    // Match the field define with its value to avoid matching the enum_define prefix
    const posField = out.indexOf("#define GPS_DYNAMIC_MODEL 6");
    expect(posConst).toBeGreaterThanOrEqual(0);
    expect(posField).toBeGreaterThan(posConst);
    expect(out).toContain("#define GPS_DYNAMIC_MODEL_AIRBORNE_1G 6");
    expect(out).toContain("#define GPS_DYNAMIC_MODEL_PORTABLE 0");
  });
});

describe("generateConfigH — compile-time guards", () => {
  it("emits GPS NMEA / I2C conflict guard after gps section", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain(
      "#if (GPS_NMEA_OUTPUT_VIA_SERIAL_PORT_ENABLE) && ((RADIO_SI5351_ENABLE) || (SENSOR_BMP280_ENABLE))"
    );
  });

  it("emits pulse counter conflict guard after sensors section", () => {
    const out = generateConfigH(makeSchema(), {});
    expect(out).toContain(
      "#if (PULSE_COUNTER_ENABLE) && ((GPS_NMEA_OUTPUT_VIA_SERIAL_PORT_ENABLE) || (RADIO_SI5351_ENABLE) || (SENSOR_BMP280_ENABLE))"
    );
  });
});
